version: '3.7'

services:
  database_api_pagamentos:
    image: postgres
    container_name: database_api_pagamentos
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api_pagamentos
    volumes:
      - pgdata:/data/postgres
  app_api_pagamentos:
    build: .
    container_name: app_api_pagamentos
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_api_pagamentos
    depends_on:
      - database_api_pagamentos

volumes:
  pgdata:
    driver: local
