version: '3.7'

services:
  api-ciclo-pagamentos-db:
    image: postgres
    container_name: api-ciclo-pagamentos-db
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ciclo-pagamentos
    volumes:
      - pgdata:/data/postgres

  api-ciclo-pagamentos-app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api-ciclo-pagamentos-app
    ports:
      - 3333:3333
    volumes:
      - .:/home/app
    depends_on:
      - api-ciclo-pagamentos-db
      - api-ciclo-pagamentos-redis

  api-ciclo-pagamentos-redis:
    image: 'bitnami/redis'
    container_name: api-ciclo-pagamentos-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  api-ciclo-pagamentos-pgadmin:
    image: dpage/pgadmin4
    container_name: api-ciclo-pagamentos-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8000:80
    depends_on:
      - api-ciclo-pagamentos-db

volumes:
  pgdata:
    driver: local
